server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: ms-gestion
          uri: http://localhost:8081
          predicates:
            # RUTAS CORREGIDAS (Sin espacios entre las comas)
            - Path=/api/gestion/**,/api/centros-medicos/**,/api/usuarios/**,/api/reservas/**,/api/lista-espera/**

  security:
    oauth2:
      resourceserver:
        jwt:
          # Esta es la ruta que contiene las llaves públicas ES256 de tu proyecto
          jwk-set-uri: https://eqmboygugsouuzoezpvh.supabase.co/auth/v1/.well-known/jwks.json
  
  logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
